---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <html>
    <head>
      <title>NGINX Node and Pod Information</title>
    </head>
    <body>
      <h1>NGINX DaemonSet</h1>
      <p>Node Information:</p>
      <ul>
        <li>Node Hostname: <strong>$NODE_NAME</strong></li>
      </ul>
      <p>Pod Information:</p>
      <ul>
        <li>Pod IP: <strong>$POD_IP</strong></li>
        <li>Pod Namespace: <strong>$POD_NAMESPACE</strong></li>
        <li>Pod Service Account: <strong>$POD_SERVICE_ACCOUNT</strong></li>
      </ul>
    </body>
    </html>
