---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
helmCharts:
- name: cert-manager
  namespace: cert-manager
  releaseName: cert-manager
  version: 1.16.1
  repo: https://charts.jetstack.io
  valuesInline:
    config:
      apiVersion: "controller.config.cert-manager.io/v1alpha1"
      kind: "ControllerConfiguration"
      enableGatewayAPI: true
    crds:
      enabled: true
