---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - namespace.yaml
helmCharts:
- name: cert-manager
  namespace: cert-manager
  includeCRDs: true
  releaseName: cert-manager
  version: 1.16.1
  repo: https://charts.jetstack.io
  valuesFile: values.yaml
