---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  kustomize.buildOptions: --enable-helm
  admin.enabled: 'false'
  statusbadge.enabled: 'true'
  users.anonymous.enabled: 'true'
  url: https://cd.nhlabs.org
  dex.config: |
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: $argocd-auth:dex.github.clientID
        clientSecret: $argocd-auth:dex.github.clientSecret
